export const arr = [
  // "Adidas",
  // "Alexander McQueen",
  "Aliexpress (marketplace)",
  "Emporio Armani",
  "Giorgio Armani",
  "Armani Exchange",
  "Audemars Piguet",
  "BOSS (Hugo Boss)",
  "Balenciaga",
  "Bally",
  "Bape (A Bathing Ape)",
  "Baxter of California",
  "Beats",
  "Belstaff",
  "Bentley (merchandise)",
  "Birkenstock",
  "Bose",
  "Bottega Veneta",
  "Brioni",
  "Burberry",
  "Bvlgari",
  "Calvin Klein",
  "Canada Goose",
  "Cartier",
  "Casio",
  "CeraVe",
  "Chanel",
  "Charlotte Tilbury",
  "Chloé",
  "Christian Louboutin",
  "Chronograph/Rolex-style watches (generic)",
  "Cinzano (spirits)",
  "Clarks",
  "Clinique",
  "Coach",
  "Converse",
  "Corrs (not typical)",
  "Daniel Wellington",
  "Dior",
  "Dolce & Gabbana",
  "Dr. Martens",
  "Dunhill",
  "Dyson",
  "Emporio Armani",
  "Estée Lauder",
  "Fendi",
  "Fila",
  "Foreo",
  "Fossil",
  "G-Shock (Casio)",
  "Giorgio Armani",
  "Giorgio Armani (Armani Jeans)",
  "Givenchy",
  "Goyard",
  "Gucci",
  "Guess",
  "H&M (fast fashion counterfeits rare)",
  "Hermès",
  "Huawei",
  "Hugo Boss",
  "IWC (watch)",
  "Jack Daniel's (bottles/spirts)",
  "Jimmy Choo",
  "Jordan (Nike Air Jordan)",
  "Kate Spade",
  "Kenzo",
  "L'Occitane",
  "LG (electronics)",
  "La Roche-Posay",
  "Lacoste",
  "Lamborghini (merch)",
  "Lancôme",
  "Levi's",
  "Longchamp",
  "Louis Vuitton",
  "MAC Cosmetics",
  "Macy's (not brand)",
  "Maybelline",
  "Michael Kors",
  "Miu Miu",
  "Moncler",
  "Montblanc",
  "Moto (motorola merch)",
  "Motorola",
  "NARS",
  "New Balance",
  "Nike",
  "Nivea",
  "Nordstrom (not brand)",
  "North Face",
  "Oakley",
  "Off-White",
  "Olaplex",
  "Omega",
  "OnePlus",
  "Oppo",
  "PUMA",
  "Paco Rabanne",
  "Panasonic",
  "Pandora",
  "Patek Philippe",
  "Paul Smith",
  "Philips",
  "Prada",
  "Pringles (novelty)",
  "Ray-Ban",
  "Reebok",
  "Rolex",
  "Samsung",
  "Seiko",
  "Sherwin-Williams (not typical)",
  "Shiseido",
  "Skechers",
  "Skinceuticals",
  "Smashbox",
  "Sony",
  "Supreme",
  "TRETORN",
  "The Ordinary",
  "Tiffany & Co.",
  "Tom Ford",
  "Tommy Hilfiger",
  "Tory Burch",
  "Under Armour",
  "Uniqlo (rare)",
  "Urban Decay",
  "Vans",
  "Versace",
  "Vichy",
  "Victoria's Secret",
  "Vuitton (Louis)",
  "Xiaomi (Mi)",
  "YSL (Saint Laurent)",
  "Yeezy (adidas/Kanye)",
  "ZARA (fast fashion knockoffs)",
  "iPad (Apple)",
  "iPhone (Apple)",
];

export const data = [
  {
    number: 1,
    trackingNumber: "TEST24040937215",
    orderNumber: "TEST24040937215",
    mawbNumber: "110-2025112449",
    actualTaxValue: 10.0,
    fileUrl: "1",
  },
];
